server:
  port: 9000
dubbo:
  application:
    id: account_consumer
    name: account_consumer
  registry:
    address: zookeeper://192.168.99.1:2181
  monitor:
    protocol: registry
  metadata-report:
    address: zookeeper://192.168.99.1:2181

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/hmily_account_1?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf8
    username: root
    password: 123456